// -------------------------------------------------------------
// 
// File Name: hdlsrc\ModelToVerilog\ToVerilog.v
// Created: 2023-11-15 16:10:41
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// DC_Out                        ce_out        1
// Env_Out                       ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ToVerilog
// Source Path: ModelToVerilog/ToVerilog
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ToVerilog
          (clk,
           reset,
           DataIn,
           DC_Out,
           Env_Out);


  input   clk;
  input   reset;
  input   signed [12:0] DataIn;  // sfix13_En2
  output  signed [12:0] DC_Out;  // sfix13_En2
  output  signed [12:0] Env_Out;  // sfix13_En2


  wire signed [12:0] FI_Full1_out1;  // sfix13_En2
  wire signed [11:0] FI_Full1_out2;  // sfix12_En1
  wire signed [12:0] Data_Type_Conversion8_out1;  // sfix13_En2


  FI_Full1 u_FI_Full1 (.clk(clk),
                       .reset(reset),
                       .IN(DataIn),  // sfix13_En2
                       .OUT(FI_Full1_out1),  // sfix13_En2
                       .Env(FI_Full1_out2)  // sfix12_En1
                       );

  assign DC_Out = FI_Full1_out1;

  assign Data_Type_Conversion8_out1 = {FI_Full1_out2, 1'b0};



  assign Env_Out = Data_Type_Conversion8_out1;

endmodule  // ToVerilog
