// -------------------------------------------------------------
// 
// File Name: hdlsrc\ModelToVerilog\FI_Full1.v
// Created: 2023-11-15 16:10:41
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FI_Full1
// Source Path: ModelToVerilog/ToVerilog/FI_Full1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FI_Full1
          (clk,
           reset,
           IN,
           OUT,
           Env);


  input   clk;
  input   reset;
  input   signed [12:0] IN;  // sfix13_En2
  output  signed [12:0] OUT;  // sfix13_En2
  output  signed [11:0] Env;  // sfix12_En1


  wire signed [64:0] GilbertTransformer_out2;  // sfix65_En53
  wire signed [65:0] Abs1_y;  // sfix66_En53
  wire signed [65:0] Abs1_cast;  // sfix66_En53
  wire signed [64:0] Abs1_out1;  // sfix65_En53
  wire signed [12:0] Subsystem_out2;  // sfix13_En2
  wire signed [12:0] GilbertTransformer_out1;  // sfix13_En2
  wire signed [13:0] Abs_y;  // sfix14_En2
  wire signed [13:0] Abs_cast;  // sfix14_En2
  wire signed [12:0] Abs_out1;  // sfix13_En2
  wire signed [11:0] Subsystem_out1;  // sfix12_En1


  assign Abs1_cast = {GilbertTransformer_out2[64], GilbertTransformer_out2};
  assign Abs1_y = (GilbertTransformer_out2 < 65'sh00000000000000000 ?  - (Abs1_cast) :
              {GilbertTransformer_out2[64], GilbertTransformer_out2});
  assign Abs1_out1 = Abs1_y[64:0];



  GilbertTransformer u_GilbertTransformer (.clk(clk),
                                           .reset(reset),
                                           .IN(Subsystem_out2),  // sfix13_En2
                                           .Xr(GilbertTransformer_out1),  // sfix13_En2
                                           .Xi(GilbertTransformer_out2)  // sfix65_En53
                                           );

  assign Abs_cast = {GilbertTransformer_out1[12], GilbertTransformer_out1};
  assign Abs_y = (GilbertTransformer_out1 < 13'sb0000000000000 ?  - (Abs_cast) :
              {GilbertTransformer_out1[12], GilbertTransformer_out1});
  assign Abs_out1 = Abs_y[12:0];



  Subsystem u_Subsystem (.clk(clk),
                         .reset(reset),
                         .IN(IN),  // sfix13_En2
                         .Xr(Abs_out1),  // sfix13_En2
                         .Xi(Abs1_out1),  // sfix65_En53
                         .Env(Subsystem_out1),  // sfix12_En1
                         .OUT(Subsystem_out2)  // sfix13_En2
                         );

  assign OUT = Subsystem_out2;

  assign Env = Subsystem_out1;

endmodule  // FI_Full1
