// -------------------------------------------------------------
// 
// File Name: hdlsrc\ModelToVerilog\DC_filter.v
// Created: 2023-11-15 16:10:41
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DC_filter
// Source Path: ModelToVerilog/ToVerilog/FI_Full1/Subsystem/DC-filter
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DC_filter
          (clk,
           reset,
           IN,
           OUT);


  input   clk;
  input   reset;
  input   signed [12:0] IN;  // sfix13_En2
  output  signed [12:0] OUT;  // sfix13_En2


  wire [15:0] Constant1_out1;  // ufix16_En16
  wire signed [20:0] Sum_out1;  // sfix21_En6
  reg signed [20:0] Delay_out1;  // sfix21_En6
  wire signed [16:0] Product_cast;  // sfix17_En16
  wire signed [37:0] Product_mul_temp;  // sfix38_En22
  wire signed [36:0] Product_cast_1;  // sfix37_En22
  wire signed [20:0] Product_out1;  // sfix21_En6
  wire signed [31:0] Sum_add_cast;  // sfix32_En6
  wire signed [31:0] Sum_add_cast_1;  // sfix32_En6
  wire signed [31:0] Sum_add_temp;  // sfix32_En6
  wire signed [15:0] Constant_out1;  // sfix16_En15
  wire signed [36:0] Product1_mul_temp;  // sfix37_En21
  wire signed [19:0] Product1_out1;  // sfix20_En5
  wire signed [31:0] Sum1_add_cast;  // sfix32_En6
  wire signed [31:0] Sum1_add_cast_1;  // sfix32_En6
  wire signed [31:0] Sum1_add_temp;  // sfix32_En6
  wire signed [12:0] Sum1_out1;  // sfix13_En2


  assign Constant1_out1 = 16'b1111100001010010;



  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 21'sb000000000000000000000;
      end
      else
        Delay_out1 <= Sum_out1;
    end



  assign Product_cast = {1'b0, Constant1_out1};
  assign Product_mul_temp = Delay_out1 * Product_cast;
  assign Product_cast_1 = Product_mul_temp[36:0];
  assign Product_out1 = Product_cast_1[36:16];



  assign Sum_add_cast = {{15{IN[12]}}, {IN, 4'b0000}};
  assign Sum_add_cast_1 = {{11{Product_out1[20]}}, Product_out1};
  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_1;
  assign Sum_out1 = Sum_add_temp[20:0];



  assign Constant_out1 = 16'sb1000000000000000;



  assign Product1_mul_temp = Delay_out1 * Constant_out1;
  assign Product1_out1 = Product1_mul_temp[35:16];



  assign Sum1_add_cast = {{11{Sum_out1[20]}}, Sum_out1};
  assign Sum1_add_cast_1 = {{11{Product1_out1[19]}}, {Product1_out1, 1'b0}};
  assign Sum1_add_temp = Sum1_add_cast + Sum1_add_cast_1;
  assign Sum1_out1 = Sum1_add_temp[16:4];



  assign OUT = Sum1_out1;

endmodule  // DC_filter
