// -------------------------------------------------------------
// 
// File Name: hdlsrc\ModelToVerilog\Subsystem.v
// Created: 2023-11-15 16:10:41
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem
// Source Path: ModelToVerilog/ToVerilog/FI_Full1/Subsystem
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem
          (clk,
           reset,
           IN,
           Xr,
           Xi,
           Env,
           OUT);


  input   clk;
  input   reset;
  input   signed [12:0] IN;  // sfix13_En2
  input   signed [12:0] Xr;  // sfix13_En2
  input   signed [64:0] Xi;  // sfix65_En53
  output  signed [11:0] Env;  // sfix12_En1
  output  signed [12:0] OUT;  // sfix13_En2


  wire signed [11:0] EnvelopeDetection_out1;  // sfix12_En1
  wire signed [12:0] DC_filter_out1;  // sfix13_En2


  EnvelopeDetection u_EnvelopeDetection (.clk(clk),
                                         .reset(reset),
                                         .Xr(Xr),  // sfix13_En2
                                         .Xi(Xi),  // sfix65_En53
                                         .Env(EnvelopeDetection_out1)  // sfix12_En1
                                         );

  assign Env = EnvelopeDetection_out1;

  DC_filter u_DC_filter (.clk(clk),
                         .reset(reset),
                         .IN(IN),  // sfix13_En2
                         .OUT(DC_filter_out1)  // sfix13_En2
                         );

  assign OUT = DC_filter_out1;

endmodule  // Subsystem
